version: '3.8'

services:
  backend:
    container_name: backend # mới được thêm
    build: ./Golbaus_BE
    ports:
      - "5000:80"
    environment:
      DBHOST: db
      DBPORT: 3306
      MYSQL_PASSWORD: "123"
      MYSQL_USER: root
      MYSQL_DATABASE: golbaus
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: golbaus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  # react:
  #   build:
  #     context: ./Golbaus_FE
  #     dockerfile: Dockerfile
  #   container_name: react
  #   volumes:
  #     - ./Golbaus_FE/build:/app/build
    # volumes:
    #   - ./Golbaus_FE/src:/app/src
    #   - ./Golbaus_FE/public:/app/public
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      #- ./default.conf:/etc/nginx/nginx.conf
      - ./Golbaus_FE/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
volumes:
  mysql_data:
  
